### ISSUE TITLE
TypeError: 'NoneType' object has no attribute 'getitem'

### ISSUE THREAD

**Issue by ak9250** [yingcong/HomoInterpGAN#2]
loading default VGG
/mnt/backup/project/ycchen/datasets/face/images/celeba_aligned/185954.jpg
Traceback (most recent call last):
  File "run.py", line 192, in <module>
    engine.run()
  File "run.py", line 187, in run
    exec ('self.{}()'.format(self.args.command))
  File "<string>", line 1, in <module>
  File "run.py", line 156, in attribute_manipulation
    img_out = [tmp for tmp in ref_loader]
  File "/usr/local/lib/python2.7/dist-packages/torch/utils/data/dataloader.py", line 615, in __next__
    batch = self.collate_fn([self.dataset[i] for i in indices])
  File "/content/HomoInterpGAN/data/attributeDataset.py", line 163, in __getitem__
    img = util.readRGB(self.files[index]).astype(np.float32)
  File "/content/HomoInterpGAN/util/util.py", line 144, in readRGB
    return img[:, :, [2, 1, 0]]
TypeError: 'NoneType' object has no attribute '__getitem__'

at 
python run.py attribute_manipulation -mp checkpoints/CelebA -sp checkpoints/CelebA/test/Smiling  --filter_target_attr Smiling -s 1 --branch_idx 0 --n_ref 5 -bs 8 --test_folder examples/aligned

**Comment by ak9250** [comment]
figured out this was due to data-dir pointing to the default location
