### ISSUE TITLE
weird results

### ISSUE THREAD

**Issue by ak9250** [yingcong/HomoInterpGAN#3]
I tried 
python run.py attribute_manipulation -mp checkpoints/CelebA -sp checkpoints/CelebA/test/Smiling  --filter_target_attr NOTSmiling -s 1 --branch_idx 0 --n_ref 5 -bs 8 --test_folder examples/aligned

and am getting weird results that lack identity preservation which is shown in the paper 
![Screen Shot 2019-06-11 at 3 42 51 PM](https://user-images.githubusercontent.com/6818285/59301524-ccf68300-8c5f-11e9-97da-94644d23f034.png)

**Comment by yingcong** [comment]
Could you send me the original image? Let me test on my side.

**Comment by ak9250** [comment]
@yingcong here is the original image
https://www.biography.com/.image/ar_1:1%2Cc_fill%2Ccs_srgb%2Cg_face%2Cq_auto:good%2Cw_300/MTE4MDAzNDEwNzMzODYwMzY2/robert-downey-jr-9542052-1-402.jpg

**Comment by ak9250** [comment]
@yingcong were you able to test it?

**Comment by yingcong** [comment]
My result is similar. I have double-checked this released code with my previous ones, which is used in the paper, but too messy to release. 
It seems the optimizer of the decoder matters. 
My previous implementation is 
self.optim_decoder = torch.optim.Adam(self.decoder.parameters(), lr=1e-4)
while in this verion it is
self.optim_decoder = torch.optim.Adam(self.decoder.parameters(), lr=1e-4,betas=[0.5, 0.999])
After changing it back, the result becomes
![0](https://user-images.githubusercontent.com/10844973/59402549-6d1fe980-8dd1-11e9-8def-cf52f15ace36.jpg)
Note that the model hasn't converged yet. I am still training it and will update a new one in the dropbox later.

**Comment by ak9250** [comment]
@yingcong ok yeah your results seem to also have the identity preservation problem, looking forward to the updated model to test out.

**Comment by yingcong** [comment]
@ak9250  I have updated the checkpoints. The results seem better than the previous one. The model keeps training and I'll have a check if the results are further improved after cvpr.

**Comment by ak9250** [comment]
@yingcong thanks, I have tried the updated checkpoints. The results do seem better now although identity is still a problem
![Screen Shot 2019-06-17 at 11 22 50 AM](https://user-images.githubusercontent.com/6818285/59593541-6dcabf80-90f2-11e9-8da6-e0d6696a279c.png)

**Comment by Feiyu-Zhang** [comment]
> @ak9250 I have updated the checkpoints. The results seem better than the previous one. The model keeps training and I'll have a check if the results are further improved after cvpr.

@ak9250 @yingcong Which is the latest pretrained model? In code ./network/model.py line:115`            model_path = 'https://www.dropbox.com/s/8lwmwfs42w5oioi/homo-decoder-8a84d0ce.pth?dl=1' 
` or link in Readme.

**Comment by yingcong** [comment]
@Feiyu-Zhang  The pretrained model is stored in the link of readme, which is https://www.dropbox.com/sh/31dki21jqaifzjj/AACPH11iwBK-38rFy8oKqeraa?dl=0 

The homo-decoder-8a84d0ce.pth is trained by simply inverting pretrained VGG feature, which is used to accelerating the training of any attributes.

**Comment by Feiyu-Zhang** [comment]
> @Feiyu-Zhang The pretrained model is stored in the link of readme, which is https://www.dropbox.com/sh/31dki21jqaifzjj/AACPH11iwBK-38rFy8oKqeraa?dl=0
> 
> The homo-decoder-8a84d0ce.pth is trained by simply inverting pretrained VGG feature, which is used to accelerating the training of any attributes.

Thanks. Which version is Python on your machine? In file `data/attributeDataset.py` line:220, `        f3 = self.frame.iloc[:, 1:] > 0
` I use Python3.7 and pandas 0.24.2. But it went wrong when I trained. The error message is as follow:

`Traceback (most recent call last):
  File "run.py", line 193, in <module>
    engine.run()
  File "run.py", line 187, in run
    exec ('self.{}()'.format(self.args.command))
  File "<string>", line 1, in <module>
  File "run.py", line 101, in train
    train_dataset, test_dataset = self.load_dataset()
  File "run.py", line 93, in load_dataset
    csv_path='info/celeba-with-orientation.csv')
  File "/nfs2/zhangfeiyu/git/HomoInterpGAN/data/attributeDataset.py", line 221, in __init__
    f3 = self.frame.iloc[:, 1:] > 0
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/ops.py", line 2108, in f
    res = self._combine_const(other, func)
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/frame.py", line 5120, in _combine_const
    return ops.dispatch_to_series(self, other, func)
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/ops.py", line 1157, in dispatch_to_series
    new_data = expressions.evaluate(column_op, str_rep, left, right)
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 208, in evaluate
    return _evaluate(op, op_str, a, b, **eval_kwargs)
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/computation/expressions.py", line 68, in _evaluate_standard
    return op(a, b)
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/ops.py", line 1128, in column_op
    for i in range(len(a.columns))}
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/ops.py", line 1128, in <dictcomp>
    for i in range(len(a.columns))}
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/ops.py", line 1766, in wrapper
    res = na_op(values, other)
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/ops.py", line 1625, in na_op
    result = _comp_method_OBJECT_ARRAY(op, x, y)
  File "/nfs2/zhangfeiyu/anaconda3/envs/py36pytorch10/lib/python3.7/site-packages/pandas/core/ops.py", line 1603, in _comp_method_OBJECT_ARRAY
    result = libops.scalar_compare(x, y, op)
  File "pandas/_libs/ops.pyx", line 97, in pandas._libs.ops.scalar_compare
TypeError: '>' not supported between instances of 'str' and 'int'`

**Comment by yingcong** [comment]
@ak9250  It seems that the problem comes from the alignment. If the model is tested on celeba-aligned dataset, then this is not a problem as all images are aligned. As the face alignment tool is not so perfect, it may sometimes lead to less appealing results due to the alignment issue. 

I have added small random shift during training, making the model less sensitive to the alignment issue. 

![5](https://user-images.githubusercontent.com/10844973/61344017-582bef80-a882-11e9-90f8-637856c4ec81.jpg)
